### ISSUE TITLE
host parameter for the HELO function

### ISSUE THREAD

**Issue by ncou** [swt83/php-smtp#14]
Hi,

Very nice lib, and very clan and simple to use.
It seems to me the "localhost" parameter isn't used.

in the constructor function there is this line :

```javascript
// set localhost
$this->localhost = $this->config('default');
```

Shouldn't it be : $this->localhost = $this->config('**localhost**'); ? because the parameter set in the config file doesn't seems to be used for the moment.

**Comment by swt83** [comment]
This code you pasted references the config array that is fed to the object when you create it.  If you look at the sample config file in the repo, it looks like this:

```
    'default' => 'primary',
    'connections' => [
        'primary' => [
            'host' => '',
            'port' => '',
            'secure' => null, // null, 'ssl', or 'tls'
            'auth' => false, // true if authorization required
            'user' => '',
            'pass' => '',
        ],
    ],
```

So ``default`` refers to the default connection as defined in the config array.

**Comment by ncou** [comment]
Whaou such a fast answer.
In the config file in the repo there is also the "localhost" string i was refering to.

```javascript
return [
    'default' => 'primary',
    'connections' => [
        'primary' => [
            'host' => '',
            'port' => '',
.....
        ],
    ],
    // NERD ONLY VARIABLE: You may want to change the origin
    // of the HELO request, as having the default value of
    // "localhost" may cause the email to be considered spam.
    // http://stackoverflow.com/questions/5294478/significance-of-localhost-in-helo-localhost
    **'localhost' => 'localhost'**, // rename to the URL you want as origin of email
];
```
It just looks like the HELO command is using the string "primary" (because it get the value of the param "default") instead of the string "localhost" configured in the array.

**Comment by ncou** [comment]
I have enabled the debug mode and i got the following log :

250 mail.smtp2go.com Hello **primary** [87.231.16.86]

So it looks like the parameter value ("localhost") defined in the config file is ignored, because the lib will use the parameter named "default" to initilize the "origin".

**Comment by swt83** [comment]
Send me pull request!

**Comment by ncou** [comment]
yes sir!

I have made the pull request.
By the way, my 2 cents opinion, but you should use simple array for the config, not really sure a lot of person will use multiple smtp configurations, and this way you could remove the dependency for the library needed for the "ex()" function. This smtp lib is simple so avoiding dependency is a good way to keep it simple :)

Close the ticket once the merge is done.
Have a good day.

**Comment by swt83** [comment]
Thank you, sir.
